#!/usr/bin/env bash
# Copyright 2022 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail
set -x

# CI Specific Steps
[[ -v PROW_JOB_ID ]] && IS_PROW=1 || IS_PROW=0
if (( IS_PROW )); then
    VERSION=v4.25.2
    BINARY=yq_linux_amd64
    gh auth login --with-token < ${GITHUB_TOKEN_PATH}
    git config --global user.name "Kubernetes Prow Robot"
    git config --global user.email "k8s.ci.robot@gmail.com"
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    apt update
    apt install gh
    wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq && chmod +x /usr/bin/yq
fi

org=$1

echo "Working on the $org organization"

# List all the repos in the organization
REPOS=$(yq '.[] | .[] | select(select(.enabled=="true")).name' alias-syncer/$org.yaml)

# Clone k/org
rm -rf /tmp/repos
gh repo clone kubernetes/org /tmp/repos/org

#Check if the OWNERS_ALIASES file exists
if test [! -f "repos/org/config/$1-OWNERS_ALIASES"]; then
    echo "OWNERS_ALIASES hasn't been created in k/org repo for $org. Please create that file and rerun this job."
    exit 1
fi

cd /tmp

# For each repo, we need to do the following:
# 1. Clone it to /tmp
# 2. Copy OWNERS_ALIASES from k/org to the /tmp/REPO/OWNERS_ALIASES
# 3. Check for diffs
# 4. If there is a diff, commit it to the owner-aliases-bump branch
# 5. Raise a PR with the diff

for repo in ${REPOS}; do
    gh repo clone $org/$repo repos/$repo
    pushd repos/$repo
    cp /tmp/repos/org/config/$1-OWNERS_ALIASES OWNERS_ALIASES
    if [[ -z "$(git status --porcelain)" ]]; then
        echo "OWNERS_ALIASES is up to date. Moving on"
        break
    fi

    gh repo fork --remote
    git checkout -b owner-aliases-bump
    git add OWNERS_ALIASES
    git commit -m "syncing OWNERS_ALIASES from kubernetes/org repository"
    git push -u origin owner-aliases-bump # default remote name set by gh cli
    gh pr create -t "Updating `OWNERS_ALIASES`" \
        -l skip-review \
        -b "This is an autogenerated PR that syncs OWNERS_ALIASES daily from kubernetes/org repository."
    popd
    rm -rf /tmp/repos/$repo
done
  
