teams:
  agent-sandbox-admins:
    description: Admin access to agent-sandbox repo
    members:
    - janetkuo
    - justinsb
    - soltysh
    privacy: closed
    repos:
      agent-sandbox: admin
  agent-sandbox-maintainers:
    description: Write access to agent-sandbox repo
    members:
    - janetkuo
    - justinsb
    - soltysh
    privacy: closed
    repos:
      agent-sandbox: write
  devops-bench-admins:
    description: Admin access to devops-bench repo
    members:
    - janetkuo
    - kow3ns
    - soltysh
    privacy: closed
    repos:
      devops-bench: admin
  devops-bench-maintainers:
    description: Write access to devops-bench repo
    members:
    - janetkuo
    - kow3ns
    - soltysh
    privacy: closed
    repos:
      devops-bench: write
  execution-hook-admins:
    description: Admin access to execution-hook repo
    members:
    - kow3ns
    privacy: closed
    repos:
      execution-hook: admin
  execution-hook-maintainers:
    description: Write access to execution-hook repo
    members:
    - jingxu97
    - kow3ns
    - xing-yang
    privacy: closed
    repos:
      execution-hook: write
  jobset-admins:
    description: Admin access to jobset repo
    members:
    - ahg-g
    - andreyvelich
    - GiuseppeTT
    - kannon92
    privacy: closed
    repos:
      jobset: admin
  jobset-maintainers:
    description: Write access to jobset repo
    members:
    - ahg-g
    - andreyvelich
    - GiuseppeTT
    - kannon92
    privacy: closed
    repos:
      jobset: write
  kjob-admins:
    description: Admin access to kjob repo
    members:
    - mimowo
    - mwielgus
    privacy: closed
    repos:
      kjob: admin
  kjob-maintainers:
    description: Write access to kjob repo
    members:
    - mimowo
    - mwielgus
    privacy: closed
    repos:
      kjob: write
  kube-agents-admins:
    description: Admin access to kube-agents repo
    members:
    - janetkuo
    - kow3ns
    - soltysh
    privacy: closed
    repos:
      kube-agents: admin
  kube-agents-maintainers:
    description: Write access to kube-agents repo
    members:
    - janetkuo
    - kow3ns
    - soltysh
    privacy: closed
    repos:
      kube-agents: write
  lws-admins:
    description: Admin access to lws repo
    members:
    - ahg-g
    - edwinhr716
    - kerthcet
    privacy: closed
    repos:
      lws: admin
  lws-maintainers:
    description: Write access to lws repo
    members:
    - ahg-g
    - edwinhr716
    - kerthcet
    privacy: closed
    repos:
      lws: write
  mcp-lifecycle-operator-admins:
    description: Admin access to mcp-lifecycle-operator repo
    members:
    - aliok
    - ArangoGutierrez
    - matzew
    - mikebrow
    - mrunalp
    - soltysh
    privacy: closed
    repos:
      mcp-lifecycle-operator: admin
  mcp-lifecycle-operator-maintainers:
    description: Write access to mcp-lifecycle-operator repo
    members:
    - aliok
    - ArangoGutierrez
    - matzew
    - mikebrow
    - mrunalp
    - soltysh
    privacy: closed
    repos:
      mcp-lifecycle-operator: write
