teams:
  wg-policy-prototypes-admins:
    description: Admin access to wg-policy-prototypes
    members:
    - ericavonb
    - hannibalhuang
    privacy: closed
    repos:
      wg-policy-prototypes: admin
  wg-policy-prototypes-maintainers:
    description: Write access to wg-policy-prototypes
    members:
    - JimBugwadia
    - rficcaglia
    privacy: closed
    repos:
      wg-policy-prototypes: write
