teams:
  cluster-autoscaler-admins:
    description: admin access to the cluster-autoscaler repo
    members:
    - adrianmoisey
    - BigDarkClown
    - jackfrancis
    - omerap12
    - towca
    - x13n
    privacy: closed
    repos:
      cluster-autoscaler: admin
  cluster-autoscaler-maintainers:
    description: write access to the cluster-autoscaler repo
    members:
    - adrianmoisey
    - BigDarkClown
    - jackfrancis
    - omerap12
    - towca
    - x13n
    privacy: closed
    repos:
      cluster-autoscaler: write
  karpenter-admins:
    description: admin access to the karpenter repo
    members:
    - adrianmoisey
    - bwagner5
    - ellistarn
    - jackfrancis
    - jonathan-innis
    - njtran
    - omerap12
    - towca
    - tzneal
    privacy: closed
    repos:
      karpenter: admin
  karpenter-maintainers:
    description: write access to the karpenter repo
    members:
    - adrianmoisey
    - bwagner5
    - ellistarn
    - jackfrancis
    - jonathan-innis
    - njtran
    - omerap12
    - towca
    - tzneal
    privacy: closed
    repos:
      karpenter: write
  karpenter-reviewers:
    description: read access to the karpenter repo
    members:
    - engedaam
    - jackfrancis
    - jmdeal      
    - tallaxes
    privacy: closed
    repos:
      karpenter: read
  karpenter-provider-ibm-cloud-admins:
    description: admin access to the karpenter-provider-ibm-cloud repo
    members:
    - pfeifferj
    privacy: closed
    repos:
      karpenter-provider-ibm-cloud: admin
  karpenter-provider-ibm-cloud-maintainers:
    description: write access to the karpenter-provider-ibm-cloud repo
    members:
    - meomnzak
    - pfeifferj
    privacy: closed
    repos:
      karpenter-provider-ibm-cloud: write
  sig-autoscaling-leads:
    description: "leads of the SIG Autoscaling"
    members:
    - adrianmoisey
    - jackfrancis
    - omerap12
    - towca
    privacy: closed
