teams:
  cloud-provider-openstack-admins:
    description: Admin access to cloud-provider-openstack repo
    members:
    - kayrus
    - mandre
    - stephenfin
    - zetaab
    privacy: closed
    repos:
      cloud-provider-openstack: admin
  cloud-provider-openstack-maintainers:
    description: Write access to the cloud-provider-openstack repo
    members:
    - kayrus
    - mandre
    - stephenfin
    - zetaab
    privacy: closed
    repos:
      cloud-provider-openstack: write
  cloud-provider-openstack-members:
    description: ""
    members:
    - gouthampacha
    - kayrus
    - mandre
    - stephenfin
    - zetaab
    privacy: closed
    repos:
      cloud-provider-openstack: read
