teams:
  legacyflag-admins:
    description: admin access to legacyflag
    members:
    - luxas
    - mtaufen
    - sttts
    privacy: closed
    repos:
      legacyflag: admin
  legacyflag-maintainers:
    description: write access to legacyflag
    members:
    - luxas
    - mtaufen
    - sttts
    privacy: closed
    repos:
      legacyflag: write
